### ISSUE TITLE
Milan

### ISSUE THREAD

**Issue by xxkat** [vlaqfn/maple.software#1]
Okay milan

**Comment by vlaqfn** [comment]
What is banning me from the server going to do?

**Comment by vlaqfn** [comment]
I can clearly still download the loader or use an alt to join the server.

**Comment by xxkat** [comment]
I'm sorry to break it to you but you're too fucking retarded to reverse engineer maple :p

**Comment by vlaqfn** [comment]
We will see when you decide to hurry up and stop acting like a disabled person and finish up your dogshit loader so I can crack it and release it for the public :)

**Comment by xxkat** [comment]
"stop acting like a disabled person" This is coming from milan...

**Comment by vlaqfn** [comment]
Who is milan?

**Comment by vlaqfn** [comment]
I really do not know.

**Comment by xxkat** [comment]
You're milan retard

**Comment by vlaqfn** [comment]
LOL Im not milan bro

**Comment by vlaqfn** [comment]
I really do not know what that is

**Comment by xxkat** [comment]
Okay milan

**Comment by vlaqfn** [comment]
Instead of typing in here go and finish your dogshit loader already.

**Comment by xxkat** [comment]
? I'm not working on maple

**Comment by vlaqfn** [comment]
So i can crack it :p im always down for a challange

**Comment by xxkat** [comment]
I can tell you that the loader will be more secure than you expect

**Comment by vlaqfn** [comment]
We will see on release.

**Comment by vlaqfn** [comment]
I will even be nice and not release it if you want me to of course.

**Comment by xxkat** [comment]
If you can reverse maple, you deserve it :p

**Comment by vlaqfn** [comment]
Anyways good luck with your protection.

**Comment by xxkat** [comment]
Not my loader :p

**Comment by vlaqfn** [comment]
I will reverse it just to use it then probably release it since i just hate ppy

**Comment by xxkat** [comment]
Why not just release your own cheat?

**Comment by vlaqfn** [comment]
Why should I do that when there is someone already working on that?

**Comment by xxkat** [comment]
You hate peppy right?

**Comment by vlaqfn** [comment]
Reversing their cheat will be much easier and will take less effort then make my own.

**Comment by vlaqfn** [comment]
Yes i truly hate him

**Comment by xxkat** [comment]
I can tell you that reversing maple is no easy task...

**Comment by xxkat** [comment]
Why don't you go crack aqn first?

**Comment by vlaqfn** [comment]
Like i said im always up for a challenge

**Comment by vlaqfn** [comment]
Outdated/trash

**Comment by xxkat** [comment]
Aqn has lots of features people would like the source to :p

**Comment by vlaqfn** [comment]
I've created many cheats in the past for many games fortnite,cd,cs,valorant

**Comment by xxkat** [comment]
Pasted*

**Comment by vlaqfn** [comment]
My loaders have yet to be cracked/reversed

**Comment by vlaqfn** [comment]
Pasted?

**Comment by xxkat** [comment]
Pasted.

**Comment by vlaqfn** [comment]
You are very funny

**Comment by vlaqfn** [comment]
Anyways good luck to you and your team.

**Comment by vlaqfn** [comment]
*your team of skids

**Comment by xxkat** [comment]
Good luck to you too, you'll need it ;p

**Comment by vlaqfn** [comment]
👯

**Comment by xxkat** [comment]
"skids"

**Comment by xxkat** [comment]
yes men pasting aqn men

**Comment by xxkat** [comment]
Okay milan

**Comment by vlaqfn** [comment]
How can I prove that I am not milan?

**Comment by xxkat** [comment]
You can't, you've already proved yourself to be milan

**Comment by vlaqfn** [comment]
Well then you have autism.

**Comment by xxkat** [comment]
Coming from milan btw

**Comment by vlaqfn** [comment]
😆

**Comment by xxkat** [comment]
https://i.imgur.com/iQhfR3a.png

Where is the proof of anything that has been skidded?

**Comment by xxkat** [comment]
The maple team knows what the fuck they are doing

**Comment by vlaqfn** [comment]
Well then why did you ban me? if you aren't afraid of anything?

**Comment by xxkat** [comment]
Because you're retarded milan

**Comment by xxkat** [comment]
Answer my question please

**Comment by xxkat** [comment]
Where is the proof of anything that has been skidded?

**Comment by vlaqfn** [comment]
Where is proof of me pasting the cheats that I made in the past?

**Comment by xxkat** [comment]
You're milan, you're retarded you can't do shit

**Comment by vlaqfn** [comment]
I am not milan. How can i prove that?

**Comment by vlaqfn** [comment]
Like deadass frfr im not milan

**Comment by xxkat** [comment]
Sorry, you've already proved that you are milan

**Comment by vlaqfn** [comment]
Alright bro we will see when yall release the loader

**Comment by xxkat** [comment]
lmfaoooooo sure

**Comment by xxkat** [comment]
You're too fucking retarded to do shit

**Comment by xxkat** [comment]
Good luck reversing a custom packer with a custom vm :p

**Comment by xxkat** [comment]
Milan?

**Comment by vlaqfn** [comment]
I really do not know why you are still typing. Like I know you are worried. - End of conversation -

**Comment by xxkat** [comment]
Well there goes milan, losing another argument ;p

**Comment by vlaqfn** [comment]
lol?

**Comment by xxkat** [comment]
You know it :D

**Comment by vlaqfn** [comment]
I can not lose if you still think I am "milan".

**Comment by vlaqfn** [comment]
Autism tbh

**Comment by xxkat** [comment]
You're milan

**Comment by vlaqfn** [comment]
🤣

**Comment by xxkat** [comment]
This issue is only making you appear more and more retarded.

**Comment by xxkat** [comment]
Do you have anything else to say or should i close this issue?

**Comment by xxkat** [comment]
I'll take that as a no

**Comment by vlaqfn** [comment]
Fucking retard lmao

**Comment by xxkat** [comment]
Oh, it's not over huh?

**Comment by xxkat** [comment]
Milan, do you even have an understanding of how most internal osu cheats work?

**Comment by vlaqfn** [comment]
Oh my god

 here we go with the milan shit again

**Comment by vlaqfn** [comment]
lmaoo

**Comment by xxkat** [comment]
Are you going to answer me?

**Comment by vlaqfn** [comment]
We will see when yall decide to release.

**Comment by xxkat** [comment]
Doesn't answer my question does it?

**Comment by xxkat** [comment]
Proving yourself more and more retarded by the minute ;p

**Comment by vlaqfn** [comment]
:p

**Comment by xxkat** [comment]
I'm waiting for an answer...

**Comment by vlaqfn** [comment]
I'm waiting for the loader to be released ;p

**Comment by xxkat** [comment]
Just proved yourself retarded once again...

**Comment by xxkat** [comment]
We both know you have absolutely no fucking idea what you're doing

**Comment by tsunyoku** [comment]
literally what the fuck is going on here LOL

**Comment by xxkat** [comment]
Milan being retarded :p

**Comment by Krul-Kun** [comment]
okay milan

**Comment by maxcutie** [comment]
**DEAN HERBERT ANTI CHEAT**

**Comment by xxkat** [comment]
facts

**Comment by xxkat** [comment]
milan, this isn't over

**Comment by maxcutie** [comment]
love u kat

**Comment by xxkat** [comment]
love you too max <3

**Comment by xxkat** [comment]
have anything you want to say to milan?

**Comment by maxcutie** [comment]
milan #offline

**Comment by maxcutie** [comment]
![image](https://user-images.githubusercontent.com/30512573/113497548-17db2d80-94ba-11eb-9e44-0047de227a26.jpeg)

**Comment by xxkat** [comment]
;p

**Comment by xxkat** [comment]
i wonder if milan will come back?

**Comment by xxkat** [comment]
we all know i've won this but

**Comment by xxkat** [comment]
it would be fucking hilarious to see him embarrass himself more

**Comment by xxkat** [comment]
this isn't over yet....

**Comment by maplesyrupuwu** [comment]
nigga can't even set up a readme, let alone being able to reverse engineer anything 😂
![image](https://user-images.githubusercontent.com/81902410/113503645-e86d0500-953b-11eb-8911-44b34ef06403.png)

**Comment by maxcutie** [comment]
![2049823746-08-03-2021](https://user-images.githubusercontent.com/30512573/113503708-5c7dbd80-94e8-11eb-8212-f7e8b2f5ec4e.jpg)
felt cute might delete later

**Comment by xxkat** [comment]
xdd

**Comment by xxkat** [comment]
polish people > americans

**Comment by xxkat** [comment]
m i l a n
